"""initial migration

Revision ID: a75e6461c6dc
Revises: 
Create Date: 2026-02-18 22:48:14.947259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.infrastructure.database.database import GUID


# revision identifiers, used by Alembic.
revision: str = 'a75e6461c6dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_units',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_units_id'), 'measurement_units', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('identification', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identification')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('inventory_sessions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('warehouse_id', GUID(length=36), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('count_number', sa.Integer(), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'month', 'count_number', name='uq_inventory_session')
    )
    op.create_index(op.f('ix_inventory_sessions_id'), 'inventory_sessions', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('inventory_unit_id', GUID(length=36), nullable=False),
    sa.Column('packaging_unit_id', GUID(length=36), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['measurement_units.id'], ),
    sa.ForeignKeyConstraint(['packaging_unit_id'], ['measurement_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('user_warehouses',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('warehouse_id', GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'warehouse_id')
    )
    op.create_table('inventory_counts',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('session_id', GUID(length=36), nullable=False),
    sa.Column('product_id', GUID(length=36), nullable=False),
    sa.Column('quantity_packages', sa.Integer(), nullable=False),
    sa.Column('quantity_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_counts_id'), 'inventory_counts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_counts_id'), table_name='inventory_counts')
    op.drop_table('inventory_counts')
    op.drop_table('user_warehouses')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_inventory_sessions_id'), table_name='inventory_sessions')
    op.drop_table('inventory_sessions')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_measurement_units_id'), table_name='measurement_units')
    op.drop_table('measurement_units')
    # ### end Alembic commands ###
